language: node_js
node_js:
  - "0.12"
  # - "0.11"
  # - "0.10"
env:
  # - >
  #   INSTALL_ETCD=2.1.1
  #   _ETCD="./etcd"
  # - >
  #   INSTALL_ETCD=2.0.13
  #   _ETCD="./etcd"
  - >
    INSTALL_ETCD=2.1.1
    _SSL="`pwd`/test/ssl"
    _ETCD="./etcd -client-cert-auth -trusted-ca-file=${_SSL}/ca.crt -cert-file=${_SSL}/server.crt -key-file=${_SSL}/server.key -advertise-client-urls https://127.0.0.1:2379 -listen-client-urls https://127.0.0.1:2379"
    JETCONFIG_SSL_CA="${_SSL}/ca.crt"
    JETCONFIG_SSL_CERT="${_SSL}/client.crt"
    JETCONFIG_SSL_KEY="${_SSL}/client.key"
before_script:
  - curl -L  https://github.com/coreos/etcd/releases/download/v${INSTALL_ETCD}/etcd-v${INSTALL_ETCD}-linux-amd64.tar.gz -o etcd-v${INSTALL_ETCD}-linux-amd64.tar.gz
  - tar xzvf etcd-v${INSTALL_ETCD}-linux-amd64.tar.gz
  - cd etcd-v${INSTALL_ETCD}-linux-amd64
  - ./etcd --version
  - ${_ETCD} &
  - cd -
  - sleep 3 # Give etcd startup time
