language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
env:
  - >
    INSTALL_ETCD=3.2.0
    _ETCD="./etcd"
  - >
    INSTALL_ETCD=2.1.1
    _ETCD="./etcd"
  - >
    INSTALL_ETCD=2.0.13
    _ETCD="./etcd"
  - >
    INSTALL_ETCD=2.1.1
    _SSL="`pwd`/test/ssl"
    _ETCD="./etcd -client-cert-auth -trusted-ca-file=${_SSL}/cacert.pem -cert-file=${_SSL}/server.crt -key-file=${_SSL}/server.key -advertise-client-urls https://127.0.0.1:2379 -listen-client-urls https://127.0.0.1:2379"
    JETCONFIG_SSL_CA="${_SSL}/cacert.pem"
    JETCONFIG_SSL_CERT="${_SSL}/client.crt"
    JETCONFIG_SSL_KEY="${_SSL}/client.key"
  - >
    INSTALL_ETCD=2.1.1
    _SSL="`pwd`/test/ssl"
    _ETCD="./etcd -trusted-ca-file=${_SSL}/cacert.pem -cert-file=${_SSL}/server.crt -key-file=${_SSL}/server.key -advertise-client-urls https://127.0.0.1:2379 -listen-client-urls https://127.0.0.1:2379"
    JETCONFIG_SSL_CA="${_SSL}/cacert.pem"
before_script:
  - curl -L  https://github.com/coreos/etcd/releases/download/v${INSTALL_ETCD}/etcd-v${INSTALL_ETCD}-linux-amd64.tar.gz -o etcd-v${INSTALL_ETCD}-linux-amd64.tar.gz
  - tar xzvf etcd-v${INSTALL_ETCD}-linux-amd64.tar.gz
  - cd etcd-v${INSTALL_ETCD}-linux-amd64
  - ./etcd --version
  - ${_ETCD} &
  - cd -
  - sleep 3 # Give etcd startup time
  # - curl -v --cacert ${JETCONFIG_SSL_CA} --cert ${JETCONFIG_SSL_CERT} --key ${JETCONFIG_SSL_KEY} https://127.0.0.1:2379/v2/keys
  # - curl -v --cacert ${JETCONFIG_SSL_CA} https://127.0.0.1:2379/v2/keys


