language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
env:
  - ETCD_VERSION=2.1.1
  - ETCD_VERSION=2.0.13
before_script:
  - curl -L  https://github.com/coreos/etcd/releases/download/v${ETCD_VERSION}/etcd-v${ETCD_VERSION}-linux-amd64.tar.gz -o etcd-v${ETCD_VERSION}-linux-amd64.tar.gz
  - tar xzvf etcd-v${ETCD_VERSION}-linux-amd64.tar.gz
  - cd etcd-v${ETCD_VERSION}-linux-amd64
  - ./etcd &
  - cd -
  - sleep 3 # Give etcd startup time
